### ISSUE TITLE
Error When Doing Maven Package

### ISSUE THREAD

**Issue by phillips1021** [UW-Madison-DoIT/angularjs-portal#356]
I cloned down the project

copied the endpoint.properties.example to endpoint.properties

Ran mvn clean package

Get this error:

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] angularjs-portal ................................... SUCCESS [  0.135 s]
[INFO] angularjs-portal-home .............................. FAILURE [  8.187 s]
[INFO] Mock Portal ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.432 s
[INFO] Finished at: 2015-11-25T12:24:13-06:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project angularjs-portal-home: Could not resolve dependencies for project edu.wisc.my.portal.angular:angularjs-portal-home:war:4.2.1.2-SNAPSHOT: Could not find artifact edu.wisc.my.apps:uw-frame:war:1.3.4-SNAPSHOT in internal (http://code.ku.edu:8082/archiva/repository/internal/) -> [Help 1]

**Comment by timlevett** [comment]
Download uw-frame and run a mvn install. Uw-frame is in the same org as this repo. Or just change the uw-frame version to 1.3.3

**Comment by phillips1021** [comment]
running mvn install on uw-frame results in this error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.863 s
[INFO] Finished at: 2015-11-25T15:47:04-06:00
[INFO] Final Memory: 14M/209M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uw-frame: Command execution failed. Cannot run program "bower" (in directory "/Users/brucephillips/git/uw-frame/src/main/webapp"): error=2, No such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uw-frame: Command execution failed.

**Comment by phillips1021** [comment]
changed the pom.xml in module angularjs-portal-home so that the version of uw-frame is 1.3.3 and was then able to build the project.

When I deploy the web.war file into Tomcat webapps where i have uPortal 4.2.1 running and then go to https://localhost:8443/web/expanded (after first logging in to uPortal using the normal uPortal URL I see the MyUW home page and what looks like an AJAX icon spinning - I don't see any of the portlets from my uPortal.

Thank you for the help - we have some managers at University of Kansas who want to see your front end with our uPortal backend.

Bruce

**Comment by timlevett** [comment]
You may have to change which tab you are asking for in the layout feed. Look at app-config.js to change URLs

**Comment by timlevett** [comment]
@phillips1021 to build `uw-frame` check the dependencies. You need to install bower on your machine.

**Comment by timlevett** [comment]
This is now fixed as 1.3.4-snapshot of frame does not exist. it was updated to point at 1.4.1-snapshot of frame which is available in central-snapshots.
