### ISSUE TITLE
Enable Travis CI for PRs

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/angularjs-portal#590]
Currently it looks like Travis only builds for commits made on the main repository.
Travis CI can also build for each PR opened on the repository.

Pros of change:
External contributions are run through CI.

Cons of change:
PRs from internal branches would be built twice.

Thoughts? :thought_balloon:

**Comment by apetro** [comment]
Changed [settings|https://travis-ci.org/UW-Madison-DoIT/angularjs-portal/settings].

![fixed](https://cloud.githubusercontent.com/assets/952283/24010154/0a05ba08-0a45-11e7-83ac-5db35660d108.png)

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
