### ISSUE TITLE
Fix Lint Errors For TravisCI

### ISSUE THREAD

**Issue by davidmsibley** [UW-Madison-DoIT/angularjs-portal#599]
I'm creating This issue to notify any developers currently working on this repository that I'm working on a wide-reaching pull request to fix lint errors.  This will touch most of the controllers, directives and services within the repository, and cause merge conflicts with any concurrent work.

(Hopefully you're not in the middle of anything @ChristianMurphy!)

**Comment by ChristianMurphy** [comment]
Thanks for the heads up @davidmsibley! 
No JavaScript changes in progress at the moment.

One small note on the lint configuration, I noticed a small correction that should happen.

```
"angular/di": "error" => "angular/di": ["error", "array"]
```

I can put together a PR if you want, or it could be incorporated as part of your planned changes.

**Comment by davidmsibley** [comment]
I'm on it, thanks!

I've changed that to
`"angular/di": "warn"`
for now.

Speaking with @thevoiceofzeke, we think the array syntax is there only due to historical precedence, so we're not going to enforce array.  However, we also won't force a change to function syntax at this moment either.  We'll encourage new edits to use function syntax and at some point in the future change that rule back to error.

**Comment by ChristianMurphy** [comment]
Array syntax also has benefits for additional minification (it allows minifiers to mangle names).
