### ISSUE TITLE
Adopt John Papa Angular Styleguide?

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/angularjs-portal#604]
Context: https://github.com/UW-Madison-DoIT/angularjs-portal/pull/601#discussion_r107953751

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
https://github.com/dustinspecker/eslint-config-angular

**Comment by apetro** [comment]
I like 

"We adopt Google Style."

because it's pithy, it's defensible, it applies across a swath of technologies and languages, it aligns with a couple of our tech choices (Angular, Material), and it's self-maintaining (presumably Google will get around to having a style guide for whatever the new hotness is whenever it comes along).

We'll probably have to make pragmatic exceptions and extensions to "We adopt Google Style." I'd like to do that as little as possible.

So, if [angularjs-google-style](https://google.github.io/styleguide/angularjs-google-style.html) can fly, I think it should.

**Comment by ChristianMurphy** [comment]
@apetro The `angularjs-google-style` guide is for using Angular specifically pulled into Google's closure compiler.
It looks like the parts of the guide that can be generalized, line up with the John Papa's styleguide and the ESLint Plugin

---

> Google Angular applications should use the 'controller as' style to export the controller onto the scope. This is fully implemented in Angular 1.2 and can be mimicked in pre-Angular 1.2 builds.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#controlleras-controller-syntax
https://github.com/dustinspecker/eslint-config-angular/blob/master/index.js#L12

---


> All DOM manipulation should be done inside directives. Directives should be kept small and use composition.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#manipulate-dom-in-a-directive

---

> Do not use $ to prepend your own object properties and service identifiers. Consider this style of naming reserved by AngularJS and jQuery.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#factory-and-service-names

**Comment by thevoiceofzeke** [comment]
[Backlogged a JIRA story to discuss this as a team.](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3263)

**Comment by davidmsibley** [comment]
After fussing with this for a while, I'm pretty certain we're currently not in a position to adhere fully to John Papa's style guide. The limiting factor at the moment is the controller-as rule. The way we have set up our directives and our controller initialization doesn't give us a straightforward path forward.

Within the MyUW team (specifically the members that attended ngConf) there's agreement that the John Papa style guide is valuable and adoption would benefit the project. We intend to use the style guide for the upgrade to Angular 4.

We need to make a decision for the current codebase, whether to adopt the style guide sans controller-as, or to leave our style guide selections as they are for the moment.

I'm very appreciative of Christian Murphy for his effort in https://github.com/UW-Madison-DoIT/angularjs-portal/pull/608. However, if we were to adopt the style guide without controller-as, I think we would want to make a new, cleaner pull request.

**Comment by ChristianMurphy** [comment]
It was just an idea I wanted to put out there, in the vein of adopting standard styleguides. :thought_balloon: 
I absolutely do not want this to be disruptive to the team's development process. :no_good_man: 
I'm going to close this ticket and the related #608 out. :no_entry_sign: 
Feel free to reused any of the pieces if you do want to adopt the styleguide, sans `controller-as` in the future.

Thanks for your time and consideration!

**Comment by davidmsibley** [comment]
Don't close the issue yet! We haven't finished!

**Comment by davidmsibley** [comment]
https://github.com/UW-Madison-DoIT/angularjs-portal/pull/615

I pulled together the changes that you made without the angular/controller-as stuff

**Comment by ChristianMurphy** [comment]
Oh? Sorry :sweat:

**Comment by davidmsibley** [comment]
Don't worry, you're not being disruptive to the development process.  This sprint I had a ticket to evaluate and work on this issue, so being active here is precisely _within_ the development process!

**Comment by davidmsibley** [comment]
Merged #615
