### ISSUE TITLE
Disable Coveralls comments

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/angularjs-portal#607]
Currently for every commit Coveralls both:

Adds a comment for the commit:
![comment](https://cloud.githubusercontent.com/assets/3107513/24426769/94a7693c-13bd-11e7-9b50-b68cabddaf26.png)

And reports to the PR status:
![pr-status](https://cloud.githubusercontent.com/assets/3107513/24426795/a63bbfea-13bd-11e7-9bd6-b2cd2998366d.png)
![maintained-for-commits](https://cloud.githubusercontent.com/assets/3107513/24426959/2efedea2-13be-11e7-8737-8f5b4b876a32.png)

Disabling the comment mechanism could keep PRs easier to read.

/cc @apetro

**Comment by apetro** [comment]
Done.

![no comment](https://cloud.githubusercontent.com/assets/952283/24519040/7918802e-1549-11e7-8f61-e9b58ead5ae8.png)

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
