### ISSUE TITLE
Glitched CI code test coverage checking

### ISSUE THREAD

**Issue by apetro** [UW-Madison-DoIT/angularjs-portal#632]
Something is goofy about our code coverage computation, as evidenced by PR #630 's documentation change bumping code coverage by 2+%.

Credit to @davidmsibley for noticing.

**Comment by ChristianMurphy** [comment]
Coverage appears to be pretty stable lately, is this still an issue?

**Comment by apetro** [comment]
Dunno. Someone can re-open this if it becomes a problem.
