### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/angularjs-portal#639]
Angular js portal is leveraging NPM and SemVer.
This combination opens up the opportunity for a lot of tooling that can help support managing depedencies.
Tools like [David-DM](https://david-dm.org/), [Depenency CI](https://dependencyci.com/), etc. Offer passive assistance, giving a highlight of when potential upgrades or fixes are needed.

Tooling could alternatively take a more active approach.
[Greenkeeper](https://greenkeeper.io/) could be added to a repository to automatically open Pull Requests when upgrades to libraries happen.
It can even retest the repository after a version has been updated, and update shrinkwrap/lock files automatically.

Thoughts? :thought_balloon:

**Comment by davidmsibley** [comment]
My gut reaction is that it couldn't hurt to add a badge with the passive stuff.  That way we can see how useful this information is before we commit to a change in commit workflow with the active.

However, I'd guess this information isn't going to be super useful, as we're going to be tied to Angular JS 1 for the near future.

**Comment by apetro** [comment]
In general, +1. In specific, lack bandwidth to engage on this until after Apereo conference next week.

**Comment by ChristianMurphy** [comment]
@UW-Madison-DoIT/uportal-home-committers would there be any objections to me switching on GreenKeeper so the project could give it a try?

**Comment by ChristianMurphy** [comment]
Wait, nvm, greenkeeper has updated so only organization admins can add the integration.
Would one of the admins be able to go to https://github.com/apps/greenkeeper/installations/new and add greenkeeper :sweat_smile:

**Comment by apetro** [comment]
I just now did, well, _something_ at https://github.com/apps/greenkeeper/installations/new to turn something on? It was confusing.

**Comment by ChristianMurphy** [comment]
That did it. :+1: 
The admin UI based of the GitHub application framework, which is new and still figuring out what a good UX is.
Thanks @apetro!
