### ISSUE TITLE
Maven release plugin conflicts with commit message hook

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/angularjs-portal#682]
the commit messages generated by the maven release plugin, cause the conventional commit check on commit messages to fail.
In order to release currently, the hook needs to be removed, then the release happens, then the hook is readded.
This is both frustrating and causes unneeded churn.

Some possible solutions:
1. configure the maven release plugin to use commit messages that align with conventional commits
2. configure the maven release plugin to skip the commitlint check when committing
3. configure commit lint to accept the messages autogenerated by the maven release plugin

**Comment by ChristianMurphy** [comment]
The Maven Release Plugins's [`scmCommentPrefix` option](https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#scmCommentPrefix) looks like it could work.

**Comment by davidmsibley** [comment]
I'd be reluctant to change Maven's scmCommentPrefix. I'll think about it some more, but something doesn't seem right about changing build behavior to accommodate commit message linting

**Comment by ChristianMurphy** [comment]
On the flip side.
It feels a bit off allowing the release plugin to make commit messages that don't quite fit in the conventional commits style and don't quite fit in the Jira style commit messages either.
The maven release plugin is off doing its own thing.

**Comment by apetro** [comment]
How soon is this going to become moot because we follow through on there's nothing actually Java about this project so it shouldn't be releasing using Maven?

**Comment by apetro** [comment]
I think I favor solution 3: "configure commit lint to accept the messages autogenerated by the maven release plugin". To be fair, I only got there seeing what (1) looks like.

**Comment by ChristianMurphy** [comment]
I'd lean against option 3.
Option 1 and 2 can be applied on the Java build.
Option 3 would need to be done in the JavaScript tooling.
My thinking is don't mess with the JavaScript tools, just to support the Java build, that will be removed soon anyway.
